# Generated by Django 5.0.6 on 2024-06-17 17:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('todo', 'todo'), ('inWork', 'inWork'), ('inReview', 'inReview'), ('done', 'done')], default='todo', max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
